### ISSUE TITLE
Option to remove the square border around the icon

### ISSUE THREAD

**Issue by YamiYukiSenpai** [psifidotos/latte-indicator-unity#11]
Can we have the option to remove the icon border?

**Comment by psifidotos** [comment]
What icon border?

**Comment by psifidotos** [comment]
Isnt that the glassy look that you can disable?

**Comment by YamiYukiSenpai** [comment]
> Isnt that the glassy look that you can disable?

I want to get rid of the icon borders entirely, not just the glassy look.  I want the only indication that the window exist are the triangles

**Comment by psifidotos** [comment]
Sorry I am not interested providing this.
