### ISSUE TITLE
Maybe borderRectangle need another border color

### ISSUE THREAD

**Issue by trmdi** [psifidotos/latte-indicator-unity#5]
It looks OK when Latte background is dark, but it doesn't look good when the Latte background is light.

For example, use `#25303030` instead of `#303030` ?

Before:
![image](https://user-images.githubusercontent.com/11857205/55963036-3e37ab00-5c9c-11e9-8d86-ddfe438b6c4a.png)

After:
![image](https://user-images.githubusercontent.com/11857205/55962801-ce292500-5c9b-11e9-8161-21bad5507ae5.png)

This make the contrast between the border and Latte background consistent between the dark and the light mode.

**Comment by psifidotos** [comment]
Your proposal adds transparency,

1. How does it look with dark background?
2. How does it look with transparent panel background with desktop background underneath?

**Comment by trmdi** [comment]
1. With dark background:
![image](https://user-images.githubusercontent.com/11857205/55974466-e5730d00-5cb1-11e9-8845-301b51bebd1d.png)

2. Without panel background + with desktop background:
![image](https://user-images.githubusercontent.com/11857205/55974605-3aaf1e80-5cb2-11e9-99b1-e0d25a6247cb.png)

I think they still look fine in any case. But this is just one suggestion...

**Comment by psifidotos** [comment]
Yep, they look much nicer!

Wanna make a PR? I will approve it
