### ISSUE TITLE
Unity Latte Dock Indicator new features

### ISSUE THREAD

**Issue by Daniel-usr** [psifidotos/latte-indicator-unity#7]
Hi, how are you? I'm from Brazil. Sorry for my bad english. I would like the unity indicator for latte dock to have the feature of all icons, including the closed ones, to have the colored indicator as pictured below. It's possible? Thank you.

![VM com barra](https://user-images.githubusercontent.com/58491226/70094822-12d64780-1602-11ea-84e2-ff5cad763ffb.jpg)

**Comment by psifidotos** [comment]
It is possible but how would you distinguish which one window in ste active one?

**Comment by Daniel-usr** [comment]
through the shapes

**Comment by Daniel-usr** [comment]
Please

**Comment by psifidotos** [comment]
Yeah, no problem when I find some time I will support it

**Comment by Daniel-usr** [comment]
thank you

**Comment by psifidotos** [comment]
![image](https://user-images.githubusercontent.com/2216474/70381605-d6824e80-1955-11ea-8019-eda2e92f1ba7.png)

**Comment by psifidotos** [comment]
![image](https://user-images.githubusercontent.com/2216474/70381608-e4d06a80-1955-11ea-85ca-f692392175ac.png)

**Comment by psifidotos** [comment]
if you need these options fast... you can download the package from master branch, extract it and in the directory that will be created you can run: 

`kpackagetool5 -u . -t Latte/Indicator`

**Comment by Daniel-usr** [comment]
I couldn't imagine you doing so fast. Congratulations. Excellent job.
