### ISSUE TITLE
Use glow color as background

### ISSUE THREAD

**Issue by Daniel-usr** [psifidotos/latte-indicator-unity#8]
Good afternoon. I really enjoyed the new functionality of unity indicator. I would like to ask one more favor (the last one). Unity indicator colors have flat, pastel colors, just like Dash to dock indicator. It's possible? If not no problem. I am grateful the same way.
PS: The last time I order something. I do not know how to program :(
![Screenshot_20191210_125525](https://user-images.githubusercontent.com/58491226/70639945-f5186c00-1c19-11ea-813a-dd99e1a368c3.png)

**Comment by psifidotos** [comment]
I did not understand, what are you asking?

**Comment by Daniel-usr** [comment]
The colors of the unity indicator are ugly. Could unity indicator colors look like dash to dock indicator colors?

**Comment by Daniel-usr** [comment]
the dash to dock indicator colors in unity indicator.

**Comment by Daniel-usr** [comment]
thank you
