### ISSUE TITLE
[feature] - glassy look for all tasks

### ISSUE THREAD

**Issue by bunnygirl-wyz** [psifidotos/latte-indicator-unity#9]
Hello there @psifidotos , how are you? I would like to suggest new features.
- Would it be possible to add an option to color only maximized windows?
- Would it be possible to add an option to disable shapes?

Just a single colored window:
![image](https://user-images.githubusercontent.com/59743084/82112036-d9ad1200-971f-11ea-884b-9f5dbb0954b8.png)

Thank you!

**Comment by psifidotos** [comment]
The first is not possible with current API

The second one it is but how you would distinguish tasks then that have multiple windows that are grouped or which one is the active one?

**Comment by bunnygirl-wyz** [comment]
- The active window would be colored.
- Minimized windows would have the default color.

I understood, even so, thank you.

**Comment by bunnygirl-wyz** [comment]
Hello there @psifidotos , how are you?
I have been thinking a little better about the issues discussed above and have come to the conclusion that it might be better not to remove the shapes by default.

The inconsistency of this extension in relation to unity would be that when applications are closed, that is, in its initial state, it should have a background color by default. it happens today only when applications are open.

| Latte dock        | Ubuntu                        |
| ------------ | -------------------------------- |
| ![image](https://user-images.githubusercontent.com/59743084/82125885-591dfe00-977f-11ea-9a58-0ffd2b25b45c.png)     | ![image](https://user-images.githubusercontent.com/59743084/82125960-cd58a180-977f-11ea-8afc-d31b6ebe3590.png)                        |

What do you think about adding the default background color of open applications in all other applications? Would be that way, however, without the active forms.
| ![image](https://user-images.githubusercontent.com/59743084/82126128-05141900-9781-11ea-99de-1e42ab0bf14f.png) |
| ------ |

**Comment by bunnygirl-wyz** [comment]
Observe the appearances:

| Correct        | Wrong                        |
| ------------ | -------------------------------- |
| ![image](https://user-images.githubusercontent.com/59743084/82126490-89679b80-9783-11ea-95cf-f4393aa7467e.png) | ![image](https://user-images.githubusercontent.com/59743084/82126517-abf9b480-9783-11ea-8562-bcf4767e4886.png) |

**Comment by psifidotos** [comment]
you mean an option to apply the Glassy look to Tasks always? there is such option for applets but I dont think it would be a problem to add an option to apply it also to Tasks

**Comment by bunnygirl-wyz** [comment]
Yes, thank you very much. ☺
